"""Calculated field generation for Bibliometrix-compatible data."""

from __future__ import annotations

import pandas as pd

from .normalizer import normalize_list_field, normalize_string


def _surname_from_author(author: str) -> str:
    """Extract a practical surname from a normalized author string."""
    text = normalize_string(author)
    if not text:
        return ""
    if "," in text:
        return text.split(",", 1)[0].strip()
    return text.split()[0].strip()


def _fallback_short_reference(row: pd.Series) -> str:
    authors = normalize_list_field(row.get("AU", []))
    surname = _surname_from_author(authors[0]) if authors else ""
    py_value = row.get("PY", 0)
    year = str(py_value) if isinstance(py_value, int) and py_value > 0 else normalize_string(py_value)
    source = normalize_string(row.get("SO", ""))
    parts = [part for part in [surname, year, source] if part]
    return ", ".join(parts)


def add_short_reference(df: pd.DataFrame) -> pd.DataFrame:
    """Add the SR (Short Reference) key.

    Per the project requirement, SR is generated by *invoking the existing
    function in the Bibliometrix-Python codebase*
    (``www.services.metatagextraction.SR`` via ``metaTagExtraction``) rather
    than reimplementing the logic. The self-contained ``_fallback_short_reference``
    is used only if that repository function cannot run for the given columns,
    so the pipeline never produces an empty/NaN SR.
    """
    output = df.copy()

    # Primary path: invoke the repository's own short-reference logic.
    try:
        from www.services.metatagextraction import metaTagExtraction

        result = metaTagExtraction(output, "SR")
        if isinstance(result, pd.DataFrame) and "SR" in result.columns:
            result["SR"] = result["SR"].apply(normalize_string)
            empty = result["SR"].str.len() == 0
            if empty.any():
                result.loc[empty, "SR"] = result.loc[empty].apply(
                    _fallback_short_reference, axis=1
                )
            return result
    except Exception:
        pass  # Fall through to the self-contained implementation.

    # Fallback only: repository function unavailable for these columns.
    if "SR" not in output.columns:
        output["SR"] = ""
    output["SR"] = output.apply(
        lambda row: normalize_string(row.get("SR")) or _fallback_short_reference(row),
        axis=1,
    )
    return output

